# Use an official node image as the base image
FROM node:21-bullseye

# Set the working directory
WORKDIR /penneyshandell_app

# Copy package.json and package-lock.json
COPY package*.json .

# Install dependencies
RUN npm ci

RUN npx playwright install --with-deps chromium

# Copy the rest of the application code
COPY . .

# Command to run the app
CMD ["npm","run","ci:test"]
